import type { CreateFranchiseDTO } from '../types';
import { slugify } from '../utils/formatters';

export interface SeedFranchise extends CreateFranchiseDTO {
  logoEmoji: string;
  industryEmoji: string;
  featured: boolean;
  viewsCount: number;
  createdDaysAgo: number;
}

export const seedFranchises: SeedFranchise[] = [
  {
    name: 'Salteñitas del Sur',
    tagline: 'La salteña más tradicional de Bolivia',
    logoEmoji: '🥟',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Cadena de salteñas artesanales con receta familiar de 30 años. Marca reconocida en Cochabamba, con proceso de producción estandarizado y alta demanda durante todo el año.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 25000,
    maxInvestment: 40000,
    royaltyPercentage: 5,
    estimatedRoi: '18%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    contactName: 'María Espinoza',
    contactEmail: 'contacto@saltenitasdelsur.bo',
    contactPhone: '+591 60711234',
    whatsapp: '+591 60711234',
    featured: true,
    viewsCount: 1240,
    createdDaysAgo: 120,
  },
  {
    name: 'Café Amazonas',
    tagline: 'Café de altura boliviano',
    logoEmoji: '☕',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Cafetería especializada en grano de las Yungas con ambiente moderno. Incluye equipamiento completo de barismo, recetas propias y proveedores directos de caficultores locales.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 35000,
    maxInvestment: 55000,
    royaltyPercentage: 6,
    estimatedRoi: '15%',
    employeesRequired: 5,
    trainingWeeks: 4,
    supportLevel: 'premium',
    contactName: 'Jorge Mendez',
    contactEmail: 'jorge@cafeamazonas.bo',
    contactPhone: '+591 71022345',
    whatsapp: '+591 71022345',
    featured: false,
    viewsCount: 980,
    createdDaysAgo: 95,
  },
  {
    name: 'Parrilla Criolla',
    tagline: 'El sabor del campo en la ciudad',
    logoEmoji: '🥩',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Restaurante de parrilla y carnes a leña con carta de cortes bolivianos. Modelo probado en Santa Cruz con operación de 25 empleados por local y alta rentabilidad detectada.',
    department: 'Santa Cruz',
    city: 'Santa Cruz de la Sierra',
    minInvestment: 45000,
    maxInvestment: 70000,
    royaltyPercentage: 7,
    estimatedRoi: '20%',
    employeesRequired: 8,
    trainingWeeks: 6,
    supportLevel: 'premium',
    contactName: 'René Suárez',
    contactEmail: 'rene@parrillacriolla.bo',
    contactPhone: '+591 71234567',
    whatsapp: '+591 71234567',
    featured: true,
    viewsCount: 1530,
    createdDaysAgo: 80,
  },
  {
    name: 'Jugos Naturales Vida',
    tagline: 'Energía natural para cada día',
    logoEmoji: '🥤',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Bar de jugos y batidos naturales de frutas de temporada. Bajo costo operativo, márgenes altos y rápida adaptación a cualquier zona comercial de Bolivia.',
    department: 'Oruro',
    city: 'Oruro',
    minInvestment: 12000,
    maxInvestment: 20000,
    royaltyPercentage: 4,
    estimatedRoi: '22%',
    employeesRequired: 2,
    trainingWeeks: 2,
    supportLevel: 'basico',
    contactName: 'Lucía Rojas',
    contactEmail: 'lucia@jugosvida.bo',
    contactPhone: '+591 72345678',
    whatsapp: '+591 72345678',
    featured: false,
    viewsCount: 640,
    createdDaysAgo: 70,
  },
  {
    name: 'Pizza Mendoza',
    tagline: 'Pizza al estilo napolitano',
    logoEmoji: '🍕',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Franquicia de pizzas artesanales con horno de piedra y delivery propio. Recetas estandarizadas, insumos centralizados y campañas de marketing ya probadas.',
    department: 'Tarija',
    city: 'Tarija',
    minInvestment: 30000,
    maxInvestment: 50000,
    royaltyPercentage: 5,
    estimatedRoi: '19%',
    employeesRequired: 5,
    trainingWeeks: 4,
    supportLevel: 'avanzado',
    contactName: 'Diego Mendoza',
    contactEmail: 'diego@pizzamendoza.bo',
    contactPhone: '+591 73456789',
    whatsapp: '+591 73456789',
    featured: false,
    viewsCount: 1120,
    createdDaysAgo: 60,
  },
  {
    name: 'Empanadas La Abuela',
    tagline: 'Receta de empanadas caseras',
    logoEmoji: '🥧',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Punto de empanadas horneadas con receta tradicional de Sucre. Inversión baja, personal mínimo y ciclo de recuperación corto para emprendedores que inician.',
    department: 'Potosí',
    city: 'Potosí',
    minInvestment: 15000,
    maxInvestment: 25000,
    royaltyPercentage: 4,
    estimatedRoi: '21%',
    employeesRequired: 3,
    trainingWeeks: 2,
    supportLevel: 'basico',
    contactName: 'Carmen Villca',
    contactEmail: 'carmen@empanadaslabuela.bo',
    contactPhone: '+591 74567890',
    whatsapp: '+591 74567890',
    featured: false,
    viewsCount: 520,
    createdDaysAgo: 55,
  },
  {
    name: 'Sushi Bol',
    tagline: 'Sushi fusión con toque andino',
    logoEmoji: '🍣',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Restaurante de sushi con fusión de insumos locales. Equipamiento incluido, carta probada y capacitación de maestros sushiman en la apertura.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 40000,
    maxInvestment: 60000,
    royaltyPercentage: 6,
    estimatedRoi: '17%',
    employeesRequired: 6,
    trainingWeeks: 5,
    supportLevel: 'avanzado',
    contactName: 'Yuri Tanaka',
    contactEmail: 'yuri@sushibol.bo',
    contactPhone: '+591 75678901',
    whatsapp: '+591 75678901',
    featured: false,
    viewsCount: 870,
    createdDaysAgo: 50,
  },
  {
    name: 'Moda Belle Époque',
    tagline: 'Moda femenina contemporánea',
    logoEmoji: '👗',
    industryEmoji: '🛍️',
    industry: 'retail',
    description:
      'Tienda de moda femenina con colecciones propias y proveedores exclusivos. Incluye visual merchandising, reposición automática y punto de venta digital.',
    department: 'Santa Cruz',
    city: 'Santa Cruz de la Sierra',
    minInvestment: 50000,
    maxInvestment: 80000,
    royaltyPercentage: 8,
    estimatedRoi: '16%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    contactName: 'Natalia Flores',
    contactEmail: 'natalia@bellleepoque.bo',
    contactPhone: '+591 76789012',
    whatsapp: '+591 76789012',
    featured: false,
    viewsCount: 930,
    createdDaysAgo: 45,
  },
  {
    name: 'Tienda TechBO',
    tagline: 'Tecnología para todos',
    logoEmoji: '💻',
    industryEmoji: '🔧',
    industry: 'tecnologia',
    description:
      'Retail de accesorios y equipos tecnológicos con servicio postventa técnico. Alianzas con marcas globales y sistema de inventario automatizado.',
    department: 'La Paz',
    city: 'El Alto',
    minInvestment: 60000,
    maxInvestment: 100000,
    royaltyPercentage: 7,
    estimatedRoi: '14%',
    employeesRequired: 5,
    trainingWeeks: 4,
    supportLevel: 'avanzado',
    contactName: 'Alan Quispe',
    contactEmail: 'alan@techbo.bo',
    contactPhone: '+591 77890123',
    whatsapp: '+591 77890123',
    featured: false,
    viewsCount: 1010,
    createdDaysAgo: 40,
  },
  {
    name: 'Hogar y Estilo',
    tagline: 'Decora tu vida con estilo',
    logoEmoji: '🏠',
    industryEmoji: '🛍️',
    industry: 'retail',
    description:
      'Tienda de decoración y artículos para el hogar con diseño de temporada. Marco de márgenes escalable y surtido rotativo internacional.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 45000,
    maxInvestment: 70000,
    royaltyPercentage: 6,
    estimatedRoi: '18%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    contactName: 'Andrea Peredo',
    contactEmail: 'andrea@hogaryestilo.bo',
    contactPhone: '+591 78901234',
    whatsapp: '+591 78901234',
    featured: false,
    viewsCount: 760,
    createdDaysAgo: 35,
  },
  {
    name: 'Mascota Feliz',
    tagline: 'Atención y productos para tu mascota',
    logoEmoji: '🐾',
    industryEmoji: '🏥',
    industry: 'salud',
    description:
      'Clínica veterinaria y tienda de mascotas con consultas, vacunas, alimentos y accesorios. Servicio recurrente de clientes con agenda y fidelización digital.',
    department: 'Beni',
    city: 'Trinidad',
    minInvestment: 35000,
    maxInvestment: 55000,
    royaltyPercentage: 5,
    estimatedRoi: '20%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'basico',
    contactName: 'Daniel Vargas',
    contactEmail: 'daniel@mascotafeliz.bo',
    contactPhone: '+591 71234560',
    whatsapp: '+591 71234560',
    featured: false,
    viewsCount: 690,
    createdDaysAgo: 30,
  },
  {
    name: 'Deportes Max',
    tagline: 'Indumentaria y accesorios deportivos',
    logoEmoji: '⚽',
    industryEmoji: '🛍️',
    industry: 'retail',
    description:
      'Tienda de ropa y artículos deportivos con marcas líderes. Incluye escaparate digital y técnicas de venta cross-selling probadas en cancha.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 40000,
    maxInvestment: 65000,
    royaltyPercentage: 6,
    estimatedRoi: '17%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'basico',
    contactName: 'Fernando Choque',
    contactEmail: 'fernando@deportesmax.bo',
    contactPhone: '+591 72345671',
    whatsapp: '+591 72345671',
    featured: false,
    viewsCount: 550,
    createdDaysAgo: 28,
  },
  {
    name: 'Limpieza Express',
    tagline: 'Profesionales de la limpieza',
    logoEmoji: '🧹',
    industryEmoji: '💼',
    industry: 'servicios',
    description:
      'Franquicia de servicios de limpieza comercial y de oficinas. Modelo de contratos recurrentes, bajo capital inicial y agilidad de crecimiento por cartera.',
    department: 'Pando',
    city: 'Cobija',
    minInvestment: 15000,
    maxInvestment: 25000,
    royaltyPercentage: 4,
    estimatedRoi: '25%',
    employeesRequired: 3,
    trainingWeeks: 2,
    supportLevel: 'basico',
    contactName: 'Silvia Mamani',
    contactEmail: 'silvia@limpiezaexpress.bo',
    contactPhone: '+591 73456782',
    whatsapp: '+591 73456782',
    featured: false,
    viewsCount: 480,
    createdDaysAgo: 25,
  },
  {
    name: 'FitZone Gym',
    tagline: 'Entrena fuerte, vive mejor',
    logoEmoji: '🏋️',
    industryEmoji: '🏋️',
    industry: 'fitness',
    description:
      'Gimnasio boutique con maquinaria de última generación y app de entrenamientos. Membresías recurrentes y programas personalizados con nutricionista.',
    department: 'Santa Cruz',
    city: 'Santa Cruz de la Sierra',
    minInvestment: 80000,
    maxInvestment: 120000,
    royaltyPercentage: 8,
    estimatedRoi: '15%',
    employeesRequired: 6,
    trainingWeeks: 5,
    supportLevel: 'premium',
    contactName: 'Víctor Ríos',
    contactEmail: 'victor@fitzone.bo',
    contactPhone: '+591 74567893',
    whatsapp: '+591 74567893',
    featured: false,
    viewsCount: 1120,
    createdDaysAgo: 22,
  },
  {
    name: 'AutoLavado Pro',
    tagline: 'Lavado y detailing automotriz',
    logoEmoji: '🚗',
    industryEmoji: '💼',
    industry: 'servicios',
    description:
      'Centro de lavado y detallado de autos con membresías por suscripción. Equipos de alta presión, productos certificados y espacio mínimo de operación.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 30000,
    maxInvestment: 50000,
    royaltyPercentage: 5,
    estimatedRoi: '19%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'basico',
    contactName: 'Marcelo Ticona',
    contactEmail: 'marcelo@autolavadopro.bo',
    contactPhone: '+591 75678904',
    whatsapp: '+591 75678904',
    featured: false,
    viewsCount: 610,
    createdDaysAgo: 18,
  },
  {
    name: 'Belleza Total',
    tagline: 'Salón de belleza y estética integral',
    logoEmoji: '💄',
    industryEmoji: '💄',
    industry: 'belleza',
    description:
      'Salón de belleza con servicios de cabello, uñas y estética facial. Cartera de clientes recurrentes y sistema de reservas online incluido.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 25000,
    maxInvestment: 40000,
    royaltyPercentage: 5,
    estimatedRoi: '21%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    contactName: 'Erika Zambrana',
    contactEmail: 'erika@belletotal.bo',
    contactPhone: '+591 76789015',
    whatsapp: '+591 76789015',
    featured: false,
    viewsCount: 540,
    createdDaysAgo: 15,
  },
  {
    name: 'Academia de Idiomas Mundo',
    tagline: 'Aprende idiomas con método probado',
    logoEmoji: '📚',
    industryEmoji: '📚',
    industry: 'educacion',
    description:
      'Academia de idiomas (inglés, portugués y guaraní) con método comunicativo. Cursos presenciales y online, con plan curricular y certificaciones.',
    department: 'Sucre',
    city: 'Sucre',
    minInvestment: 20000,
    maxInvestment: 35000,
    royaltyPercentage: 6,
    estimatedRoi: '18%',
    employeesRequired: 4,
    trainingWeeks: 4,
    supportLevel: 'avanzado',
    contactName: 'Patricia Camacho',
    contactEmail: 'patricia@academiamundo.bo',
    contactPhone: '+591 77890126',
    whatsapp: '+591 77890126',
    featured: false,
    viewsCount: 470,
    createdDaysAgo: 12,
  },
  {
    name: 'Code Academy Bolivia',
    tagline: 'Programación para el futuro',
    logoEmoji: '👨‍💻',
    industryEmoji: '📚',
    industry: 'educacion',
    description:
      'Academia de programación con bootcamps de desarrollo web y móvil. Plataforma de aprendizaje propia, mentores certificados y bolsa de empleo.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 40000,
    maxInvestment: 60000,
    royaltyPercentage: 7,
    estimatedRoi: '16%',
    employeesRequired: 5,
    trainingWeeks: 5,
    supportLevel: 'premium',
    contactName: 'Gustavo Arce',
    contactEmail: 'gustavo@codeacademy.bo',
    contactPhone: '+591 78901237',
    whatsapp: '+591 78901237',
    featured: false,
    viewsCount: 880,
    createdDaysAgo: 8,
  },
  {
    name: 'Kids Learning',
    tagline: 'Educación inicial con diversión',
    logoEmoji: '🧒',
    industryEmoji: '📚',
    industry: 'educacion',
    description:
      'Centro de estimulación temprana e inglés para niños de 3 a 7 años. Material didáctico propio, metodología lúdica y padres que recomiendan.',
    department: 'Santa Cruz',
    city: 'Santa Cruz de la Sierra',
    minInvestment: 30000,
    maxInvestment: 45000,
    royaltyPercentage: 6,
    estimatedRoi: '20%',
    employeesRequired: 5,
    trainingWeeks: 4,
    supportLevel: 'avanzado',
    contactName: 'Melissa Antelo',
    contactEmail: 'melissa@kidslearning.bo',
    contactPhone: '+591 71234598',
    whatsapp: '+591 71234598',
    featured: false,
    viewsCount: 520,
    createdDaysAgo: 5,
  },
  {
    name: 'Marketing Digital BO',
    tagline: 'Agencia de marketing digital',
    logoEmoji: '📱',
    industryEmoji: '🔧',
    industry: 'tecnologia',
    description:
      'Agencia de marketing digital con clientes recurrentes en todo el país. Servicios de pauta, redes sociales y SEO con equipo remoto y softwares propios.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 25000,
    maxInvestment: 40000,
    royaltyPercentage: 5,
    estimatedRoi: '22%',
    employeesRequired: 3,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    contactName: 'Bruno Orellana',
    contactEmail: 'bruno@mdbo.bo',
    contactPhone: '+591 72345619',
    whatsapp: '+591 72345619',
    featured: false,
    viewsCount: 660,
    createdDaysAgo: 2,
  },
];

export function buildSeedRows(dbNowDaysAgo: number): {
  sql: string;
  params: (string | number | null)[][];
} {
  const now = Date.now();
  const rows: (string | number | null)[][] = [];

  for (const f of seedFranchises) {
    const createdAt = new Date(now - f.createdDaysAgo * 86400000)
      .toISOString()
      .replace('T', ' ')
      .slice(0, 19);
    const updatedAt = createdAt;
    rows.push([
      null,
      f.name,
      slugify(f.name),
      f.logoEmoji,
      f.tagline ?? null,
      f.description,
      f.industry,
      f.industryEmoji,
      'Bolivia',
      f.department,
      f.city,
      f.minInvestment,
      f.maxInvestment,
      'USD',
      f.royaltyPercentage,
      'mensual',
      f.estimatedRoi ?? null,
      f.employeesRequired,
      f.trainingWeeks,
      f.supportLevel,
      f.website ?? null,
      f.contactName,
      f.contactEmail,
      f.contactPhone ?? null,
      f.whatsapp ?? null,
      f.featured ? 1 : 0,
      'activa',
      f.viewsCount,
      0,
      createdAt,
      updatedAt,
    ]);
  }

  const sql = `
    INSERT INTO franchises (
      user_id, name, slug, logo_emoji, tagline, description, industry,
      industry_emoji, country, department, city, min_investment, max_investment,
      currency, royalty_percentage, royalty_type, estimated_roi, employees_required,
      training_weeks, support_level, website, contact_name, contact_email,
      contact_phone, whatsapp, featured, status, views_count, inquiries_count,
      created_at, updated_at
    ) VALUES (
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
    );
  `;

  return { sql, params: rows };
}