import type { CreateFranchiseDTO } from '../types';
import { slugify } from '../utils/formatters';

export interface SeedMilestone {
  title: string;
  targetDate?: string;
  completed?: boolean;
}

export interface SeedFranchise extends CreateFranchiseDTO {
  logoEmoji: string;
  industryEmoji: string;
  featured: boolean;
  viewsCount: number;
  createdDaysAgo: number;
  segment?: 'franquicia' | 'sociedad' | 'proyecto' | 'mipe';
  subtype?: string;
  availablePercentage?: number;
  projectStart?: string;
  projectEnd?: string;
  mipeStage?: 'idea' | 'validado' | 'operativo';
  pitch?: string;
  videoUrl?: string;
  formalizationPlan?: string;
  milestones?: SeedMilestone[];
}

export const seedFranchises: SeedFranchise[] = [
  {
    name: 'Salteñitas del Sur',
    tagline: 'La salteña jujeña con alma cochabambina',
    logoEmoji: '🥟',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Cadena de salteñas artesanales fundada en 1994 en el mercado La Cancha. Masa liviana calcha, jugo resbaloso y receta familiar con 3 décadas de tradición. Hoy opera 7 puntos en Cochabamba (Cala Cala, Av. América y Blanco Galindo) con producción centralizada en Quillacollo y franquicias en 2 departamentos. El modelo incluye recetario estandarizado, cámara de fermentación y contrato de suministro de insumos.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 28000,
    maxInvestment: 45000,
    royaltyPercentage: 5,
    estimatedRoi: '18%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    website: 'www.saltenitasdelsur.bo',
    contactName: 'María Espinoza',
    contactEmail: 'franquicias@saltenitasdelsur.bo',
    contactPhone: '+591 60711234',
    whatsapp: '+591 60711234',
    featured: true,
    viewsCount: 1240,
    createdDaysAgo: 120,
  },
  {
    name: 'Café Amazonas',
    tagline: 'Café de altura de los Yungas, tostado en origen',
    logoEmoji: '☕',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Cafetería de especialidad con grano de Caranavi y Coroico (1.600 m s. n. m.), tostado propio cada semana. Formato probado en Sopocachi y Zona Sur de La Paz con ticket promedio de Bs 32. Incluye barra de barismo, capacitación certificada, cartas estacionales y convenio directo con 14 familias cafetaleras. Ideal para avenidas comerciales y zonas de oficinas.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 38000,
    maxInvestment: 58000,
    royaltyPercentage: 6,
    estimatedRoi: '15%',
    employeesRequired: 5,
    trainingWeeks: 4,
    supportLevel: 'premium',
    website: 'www.cafeamazonas.bo',
    contactName: 'Jorge Mendez',
    contactEmail: 'franquicias@cafeamazonas.bo',
    contactPhone: '+591 71022345',
    whatsapp: '+591 71022345',
    featured: false,
    viewsCount: 980,
    createdDaysAgo: 95,
  },
  {
    name: 'Parrilla Criolla',
    tagline: 'Cortes bolivianos a la leña, tradición cruceña',
    logoEmoji: '🥩',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Restaurante de carnes a la parrilla con cortes de Vallecito y proveedores ganaderos del Chiquitano. Local insignia en Equipetrol (Santa Cruz) con aforo para 80 personas y show de parrilla a la vista. El paquete de franquicia incluye obra civil llave en mano, extractor industrial, carta de 40 platos y sistema POS con control de merma. Fin de semana con rotación de 3 veces mesa.',
    department: 'Santa Cruz',
    city: 'Santa Cruz de la Sierra',
    minInvestment: 48000,
    maxInvestment: 75000,
    royaltyPercentage: 7,
    estimatedRoi: '20%',
    employeesRequired: 8,
    trainingWeeks: 6,
    supportLevel: 'premium',
    website: 'www.parrillacriolla.bo',
    contactName: 'René Suárez',
    contactEmail: 'expansion@parrillacriolla.bo',
    contactPhone: '+591 71234567',
    whatsapp: '+591 71234567',
    featured: true,
    viewsCount: 1530,
    createdDaysAgo: 80,
  },
  {
    name: 'Jugos Naturales Vida',
    tagline: 'Vitaminas frescas al paso, de La Paz a Potosí',
    logoEmoji: '🥤',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Bar de jugos y licuados con fruta de temporada del mercado Rodríguez de La Paz. Formato isla de 6 m² para galerías comerciales, universidades y pasajes peatonales. Inversión de las más bajas del mercado: licuadora industrial, exhibidor refrigerado y contrato de fruta con 2 proveedores fijos. Punto de equilibrio alcanzado entre el mes 8 y 12 según la ubicación.',
    department: 'Oruro',
    city: 'Oruro',
    minInvestment: 12000,
    maxInvestment: 20000,
    royaltyPercentage: 4,
    estimatedRoi: '22%',
    employeesRequired: 2,
    trainingWeeks: 2,
    supportLevel: 'basico',
    website: 'www.jugosvida.bo',
    contactName: 'Lucía Rojas',
    contactEmail: 'info@jugosvida.bo',
    contactPhone: '+591 72345678',
    whatsapp: '+591 72345678',
    featured: false,
    viewsCount: 640,
    createdDaysAgo: 70,
  },
  {
    name: 'Pizza Mendoza',
    tagline: 'Pizza al estilo napolitano con horno de barro chapaco',
    logoEmoji: '🍕',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Pizzería artesanal con masa de fermentación de 48 horas y horno de barro, nacida en Tarija para acompañar el vino de la región. Delivery propio con flota de motos y app de pedidos con seguimiento. La franquicia incluye central de masas (o receta para producción local), branding completo y campañas de marketing digital gestionadas por la matriz.',
    department: 'Tarija',
    city: 'Tarija',
    minInvestment: 30000,
    maxInvestment: 50000,
    royaltyPercentage: 5,
    estimatedRoi: '19%',
    employeesRequired: 5,
    trainingWeeks: 4,
    supportLevel: 'avanzado',
    website: 'www.pizzamendoza.bo',
    contactName: 'Diego Mendoza',
    contactEmail: 'franquicias@pizzamendoza.bo',
    contactPhone: '+591 73456789',
    whatsapp: '+591 73456789',
    featured: false,
    viewsCount: 1120,
    createdDaysAgo: 60,
  },
  {
    name: 'Empanadas La Abuela',
    tagline: 'La empanada charqueña como en casa',
    logoEmoji: '🥧',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Punto de empanadas horneadas con receta familiar de Sucre, rellenas de charque, queso criollo y jigote. Modelo pensado para emprendedores que inician: local de 12 m², horno convector y 2 personas de staff. Producción semiserializada con congelado de 500 unidades para picos de demanda (fiestas patrias y Semana Santa).',
    department: 'Potosí',
    city: 'Potosí',
    minInvestment: 15000,
    maxInvestment: 25000,
    royaltyPercentage: 4,
    estimatedRoi: '21%',
    employeesRequired: 3,
    trainingWeeks: 2,
    supportLevel: 'basico',
    website: 'www.empanadaslabuela.bo',
    contactName: 'Carmen Villca',
    contactEmail: 'carmen@empanadaslabuela.bo',
    contactPhone: '+591 74567890',
    whatsapp: '+591 74567890',
    featured: false,
    viewsCount: 520,
    createdDaysAgo: 55,
  },
  {
    name: 'Sushi Bol',
    tagline: 'Fusión nikkei con trucha de los Andes',
    logoEmoji: '🍣',
    industryEmoji: '🍔',
    industry: 'comida',
    description:
      'Restaurante de sushi fusión con trucha de lago (Copacabana) y productos andinos, creado por la segunda generación de la colectividad nikkei en La Paz. Barra de 10 puestos más salón de 40, entregas en Zona Sur y Calacoto. La matriz envía un sushiman instructor durante las 2 primeras semanas de apertura y certifica al equipo local.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 42000,
    maxInvestment: 62000,
    royaltyPercentage: 6,
    estimatedRoi: '17%',
    employeesRequired: 6,
    trainingWeeks: 5,
    supportLevel: 'avanzado',
    website: 'www.sushibol.bo',
    contactName: 'Yuri Tanaka',
    contactEmail: 'yuri@sushibol.bo',
    contactPhone: '+591 75678901',
    whatsapp: '+591 75678901',
    featured: false,
    viewsCount: 870,
    createdDaysAgo: 50,
  },
  {
    name: 'Moda Belle Époque',
    tagline: 'Moda femenina con diseño cruceño',
    logoEmoji: '👗',
    industryEmoji: '🛍️',
    industry: 'retail',
    description:
      'Tienda de moda femenina con taller propio en Santa Cruz y colecciones cápsula cada 45 días. 9 locales en 3 departamentos con reposición automática y sistema de punto de venta integrado. La franquicia incluye visual merchandising profesional, campañas fotográficas y exclusividad zonal de 2 km a la redonda. Rotación de inventario objetivo: 4 veces al año.',
    department: 'Santa Cruz',
    city: 'Santa Cruz de la Sierra',
    minInvestment: 52000,
    maxInvestment: 82000,
    royaltyPercentage: 8,
    estimatedRoi: '16%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    website: 'www.belleepoque.bo',
    contactName: 'Natalia Flores',
    contactEmail: 'franquicias@belleepoque.bo',
    contactPhone: '+591 76789012',
    whatsapp: '+591 76789012',
    featured: false,
    viewsCount: 930,
    createdDaysAgo: 45,
  },
  {
    name: 'Tienda TechBO',
    tagline: 'Tecnología con garantía y servicio técnico propio',
    logoEmoji: '💻',
    industryEmoji: '🔧',
    industry: 'tecnologia',
    description:
      'Retail de tecnología y accesorios con servicio técnico certificado en garantías, nacido en El Alto y con 5 sucursales en La Paz. Convenios de distribución con marcas globales e importación directa vía Iquique. Sistema de inventario en la nube con alertas de stock y facturación electrónica integrada. Público objetivo: estudiantes y pequeños negocios.',
    department: 'La Paz',
    city: 'El Alto',
    minInvestment: 60000,
    maxInvestment: 100000,
    royaltyPercentage: 7,
    estimatedRoi: '14%',
    employeesRequired: 5,
    trainingWeeks: 4,
    supportLevel: 'avanzado',
    website: 'www.techbo.bo',
    contactName: 'Alan Quispe',
    contactEmail: 'expansion@techbo.bo',
    contactPhone: '+591 77890123',
    whatsapp: '+591 77890123',
    featured: false,
    viewsCount: 1010,
    createdDaysAgo: 40,
  },
  {
    name: 'Hogar y Estilo',
    tagline: 'Decoración andina contemporánea',
    logoEmoji: '🏠',
    industryEmoji: '🛍️',
    industry: 'retail',
    description:
      'Tienda de decoración y hogar con líneas de textiles andinos reinterpretados (tejidos de Ovejería y aguayos de Torotoro). Surtido rotativo importado más línea propia hecha con artesanos locales. Local tipo showroom de 60 m² con escenografía renovada por temporada. Márgenes del 52% en línea propia y estrategia de combos de regalo para fechas comerciales.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 45000,
    maxInvestment: 70000,
    royaltyPercentage: 6,
    estimatedRoi: '18%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    website: 'www.hogaryestilo.bo',
    contactName: 'Andrea Peredo',
    contactEmail: 'andrea@hogaryestilo.bo',
    contactPhone: '+591 78901234',
    whatsapp: '+591 78901234',
    featured: false,
    viewsCount: 760,
    createdDaysAgo: 35,
  },
  {
    name: 'Mascota Feliz',
    tagline: 'Clínica veterinaria y pet shop en un solo lugar',
    logoEmoji: '🐾',
    industryEmoji: '🏥',
    industry: 'salud',
    description:
      'Clínica veterinaria con consultorio, vacunación, grooming y pet shop integrado. Formato probado en Trinidad con 380 pacientes activos y plan de salud preventiva por suscripción (Bs 89/mes). La franquicia incluye protocolos clínicos, software de historiales en la nube, alianza con laboratorio veterinario y acompañamiento del médico veterinario corporativo durante la apertura.',
    department: 'Beni',
    city: 'Trinidad',
    minInvestment: 35000,
    maxInvestment: 55000,
    royaltyPercentage: 5,
    estimatedRoi: '20%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'basico',
    website: 'www.mascotafeliz.bo',
    contactName: 'Daniel Vargas',
    contactEmail: 'franquicias@mascotafeliz.bo',
    contactPhone: '+591 71234560',
    whatsapp: '+591 71234560',
    featured: false,
    viewsCount: 690,
    createdDaysAgo: 30,
  },
  {
    name: 'Deportes Max',
    tagline: 'Indumentaria deportiva para el altiplano',
    logoEmoji: '⚽',
    industryEmoji: '🛍️',
    industry: 'retail',
    description:
      'Tienda de ropa y accesorios deportivos con licencias oficiales de la Selección Boliviana y clubes de la División Profesional. Escaparate digital con pantallas y probadores temáticos. Estrategia de venta cruzada (botín + espinilleras + medias) probada con ticket promedio de Bs 420. Temporadas fuertes: Copa América, clasificatorias y fiestas patrias.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 40000,
    maxInvestment: 65000,
    royaltyPercentage: 6,
    estimatedRoi: '17%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'basico',
    website: 'www.deportesmax.bo',
    contactName: 'Fernando Choque',
    contactEmail: 'ventas@deportesmax.bo',
    contactPhone: '+591 72345671',
    whatsapp: '+591 72345671',
    featured: false,
    viewsCount: 550,
    createdDaysAgo: 28,
  },
  {
    name: 'Limpieza Express',
    tagline: 'Limpieza profesional para oficinas y comercios',
    logoEmoji: '🧹',
    industryEmoji: '💼',
    industry: 'servicios',
    description:
      'Empresa de limpieza comercial con cartera de contratos recurrentes en Cobija (bancos, oficinas públicas y comercios). Modelo de negocio B2B con facturación mensual predecible: el franquiciado hereda 5 contratos iniciales firmados por la matriz. Incluye maquinaria (autolavadoras, vapor), uniformes, insumios ecosertificados y capacitación en protocolos de bioseguridad.',
    department: 'Pando',
    city: 'Cobija',
    minInvestment: 15000,
    maxInvestment: 25000,
    royaltyPercentage: 4,
    estimatedRoi: '25%',
    employeesRequired: 3,
    trainingWeeks: 2,
    supportLevel: 'basico',
    website: 'www.limpiezaexpress.bo',
    contactName: 'Silvia Mamani',
    contactEmail: 'silvia@limpiezaexpress.bo',
    contactPhone: '+591 73456782',
    whatsapp: '+591 73456782',
    featured: false,
    viewsCount: 480,
    createdDaysAgo: 25,
  },
  {
    name: 'FitZone Gym',
    tagline: 'Gimnasio boutique 24/7 con app incluida',
    logoEmoji: '🏋️',
    industryEmoji: '🏋️',
    industry: 'fitness',
    description:
      'Gimnasio boutique de 350 m² con acceso 24/7 mediante tarjeta RFID y app con rutinas, nutrición y reserva de clases. Sede insignia en Equipetrol con 900 miembros activos y cancelación mensual inferior al 4%. La franquicia incluye el layout validado de maquinaria (proveedor directo con descuento corporativo), plan de lanzamiento con campaña de 100 membresías fundacionales y acompañamiento del coach corporativo.',
    department: 'Santa Cruz',
    city: 'Santa Cruz de la Sierra',
    minInvestment: 80000,
    maxInvestment: 120000,
    royaltyPercentage: 8,
    estimatedRoi: '15%',
    employeesRequired: 6,
    trainingWeeks: 5,
    supportLevel: 'premium',
    website: 'www.fitzone.bo',
    contactName: 'Víctor Ríos',
    contactEmail: 'franquicias@fitzone.bo',
    contactPhone: '+591 74567893',
    whatsapp: '+591 74567893',
    featured: false,
    viewsCount: 1120,
    createdDaysAgo: 22,
  },
  {
    name: 'AutoLavado Pro',
    tagline: 'Lavado y detailing con membresías mensuales',
    logoEmoji: '🚗',
    industryEmoji: '💼',
    industry: 'servicios',
    description:
      'Centro de lavado y detallado automotriz con túnel de espuma activa y 3 bahías de detailing. Modelo de ingresos recurrentes: plan mensual de lavados ilimitados (Bs 149/mes) que ya cubre el 45% de los costos fijos en la sede de Miraflores. Incluye equipos de ósmosis para secado sin marcas, proveedor de químicos certificado y canal de agendamiento por WhatsApp Business.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 30000,
    maxInvestment: 50000,
    royaltyPercentage: 5,
    estimatedRoi: '19%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'basico',
    website: 'www.autolavadopro.bo',
    contactName: 'Marcelo Ticona',
    contactEmail: 'marcelo@autolavadopro.bo',
    contactPhone: '+591 75678904',
    whatsapp: '+591 75678904',
    featured: false,
    viewsCount: 610,
    createdDaysAgo: 18,
  },
  {
    name: 'Belleza Total',
    tagline: 'Salón integral con reservas online',
    logoEmoji: '💄',
    industryEmoji: '💄',
    industry: 'belleza',
    description:
      'Salón de belleza y estética integral (cabello, uñas, pestañas y facial) con sistema de reservas online y recordatorios automáticos por WhatsApp. 3 sedes en Cochabamba con cartera de 1.200 clientas y recompra mensual del 62%. La franquicia incluye equipamiento completo de peluquería, línea de tratamiento exclusiva y programa de fidelización con acumulación de puntos.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 25000,
    maxInvestment: 40000,
    royaltyPercentage: 5,
    estimatedRoi: '21%',
    employeesRequired: 4,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    website: 'www.bellezatotal.bo',
    contactName: 'Erika Zambrana',
    contactEmail: 'franquicias@bellezatotal.bo',
    contactPhone: '+591 76789015',
    whatsapp: '+591 76789015',
    featured: false,
    viewsCount: 540,
    createdDaysAgo: 15,
  },
  {
    name: 'Academia de Idiomas Mundo',
    tagline: 'Inglés, portugués y quechua con método conversacional',
    logoEmoji: '📚',
    industryEmoji: '📚',
    industry: 'educacion',
    description:
      'Academia de idiomas fundada en Sucre con método conversacional de 6 niveles y grupos de máximo 10 estudiantes. Modalidad presencial y online sincrónica, con certificación al finalizar cada nivel y convenios con universidades locales para prácticas. La franquicia incluye plan curricular completo, plataforma LMS, material didáctico propio y capacitación docente anual.',
    department: 'Sucre',
    city: 'Sucre',
    minInvestment: 20000,
    maxInvestment: 35000,
    royaltyPercentage: 6,
    estimatedRoi: '18%',
    employeesRequired: 4,
    trainingWeeks: 4,
    supportLevel: 'avanzado',
    website: 'www.academiamundo.bo',
    contactName: 'Patricia Camacho',
    contactEmail: 'patricia@academiamundo.bo',
    contactPhone: '+591 77890126',
    whatsapp: '+591 77890126',
    featured: false,
    viewsCount: 470,
    createdDaysAgo: 12,
  },
  {
    name: 'Code Academy Bolivia',
    tagline: 'Bootcamps de programación con bolsa de empleo',
    logoEmoji: '👨‍💻',
    industryEmoji: '📚',
    industry: 'educacion',
    description:
      'Academia de programación con bootcamps de 16 semanas en desarrollo web y móvil (JavaScript, React, React Native). Cohortes híbridas en La Paz con 84% de empleabilidad a los 6 meses y bolsa de empleo con 30 empresas aliadas. La franquicia incluye plataforma de aprendizaje propia, plan de estudios versionado, mentores certificados y guía para postular a fondos de emprendimiento tecnológico.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 40000,
    maxInvestment: 60000,
    royaltyPercentage: 7,
    estimatedRoi: '16%',
    employeesRequired: 5,
    trainingWeeks: 5,
    supportLevel: 'premium',
    website: 'www.codeacademy.bo',
    contactName: 'Gustavo Arce',
    contactEmail: 'gustavo@codeacademy.bo',
    contactPhone: '+591 78901237',
    whatsapp: '+591 78901237',
    featured: false,
    viewsCount: 880,
    createdDaysAgo: 8,
  },
  {
    name: 'Kids Learning',
    tagline: 'Estimulación temprana e inglés para niños',
    logoEmoji: '🧒',
    industryEmoji: '📚',
    industry: 'educacion',
    description:
      'Centro de estimulación temprana e inglés para niños de 3 a 7 años con metodología lúdica y aulas temáticas. Sedes en Santa Cruz con 240 familias activas y tasa de recomendación del 91%. La franquicia incluye mobiliario a escala infantil, material didáctico propio (kit de 120 actividades), formación en primeros auxilios pediátricos y plan de marketing escolar con alianzas a colegios.',
    department: 'Santa Cruz',
    city: 'Santa Cruz de la Sierra',
    minInvestment: 30000,
    maxInvestment: 45000,
    royaltyPercentage: 6,
    estimatedRoi: '20%',
    employeesRequired: 5,
    trainingWeeks: 4,
    supportLevel: 'avanzado',
    website: 'www.kidslearning.bo',
    contactName: 'Melissa Antelo',
    contactEmail: 'melissa@kidslearning.bo',
    contactPhone: '+591 71234598',
    whatsapp: '+591 71234598',
    featured: false,
    viewsCount: 520,
    createdDaysAgo: 5,
  },
  {
    name: 'Marketing Digital BO',
    tagline: 'Agencia digital para pymes bolivianas',
    logoEmoji: '📱',
    industryEmoji: '🔧',
    industry: 'tecnologia',
    description:
      'Agencia de marketing digital especializada en pymes: pauta en Facebook e Instagram, Google Ads, diseño de marca y gestión de WhatsApp Business. Cartera de 60 clientes con contratos mensuales recurrentes en 4 departamentos. Modelo ejecutable con equipo híbrido (2 presenciales + remoto). La franquicia incluye licencias de software, plantillas de campañas por rubro y kit comercial con argumentario de venta.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 25000,
    maxInvestment: 40000,
    royaltyPercentage: 5,
    estimatedRoi: '22%',
    employeesRequired: 3,
    trainingWeeks: 3,
    supportLevel: 'avanzado',
    website: 'www.mdbo.bo',
    contactName: 'Bruno Orellana',
    contactEmail: 'bruno@mdbo.bo',
    contactPhone: '+591 72345619',
    whatsapp: '+591 72345619',
    featured: false,
    viewsCount: 660,
    createdDaysAgo: 2,
  },
  {
    name: 'Distribuidora Andina SRL',
    tagline: 'Capital social disponible para ampliar cobertura regional',
    logoEmoji: '🏭',
    industryEmoji: '📦',
    industry: 'distribución',
    description:
      'SRL constituida ante SEPREC con 6 años de operación en la distribución de abarrotes entre La Paz y El Alto. Cuenta con flota propia de 5 vehículos, 3 centros de acopio y cartera de 420 puntos de venta activos. Se ofrece capital social para expandir la cobertura a Cochabamba y duplicar la flota.',
    department: 'La Paz',
    city: 'La Paz',
    minInvestment: 50000,
    maxInvestment: 50000,
    royaltyPercentage: 0,
    employeesRequired: 12,
    trainingWeeks: 1,
    supportLevel: 'basico',
    contactName: 'Carlos Quisbert',
    contactEmail: 'inversiones@distribuidoraandina.bo',
    contactPhone: '+591 70011223',
    featured: false,
    viewsCount: 410,
    createdDaysAgo: 30,
    segment: 'sociedad',
    subtype: 'srl',
    availablePercentage: 30,
    pitch:
      'Compra de capital social: el inversionista ingresa al objeto social de la SRL con participación proporcional y responsabilidad limitada al aporte.',
  },
  {
    name: 'Laboratorio Clínico Santa Bárbara SRL',
    tagline: 'Capital social para segundo laboratorio en el norte',
    logoEmoji: '🧪',
    industryEmoji: '🏥',
    industry: 'salud',
    description:
      'Laboratorio clínico con 8 años en Cochabamba, procesa 900 muestras mensuales con convenios con 4 clínicas privadas. Certificación ISO 9001 en trámite. Busca socios capitalistas para abrir una segunda sede en la zona norte con equipamiento de hematology y bioquímica de última generación.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 85000,
    maxInvestment: 85000,
    royaltyPercentage: 0,
    employeesRequired: 6,
    trainingWeeks: 1,
    supportLevel: 'basico',
    contactName: 'Dra. Patricia Salazar',
    contactEmail: 'gerencia@labsantabarbara.bo',
    contactPhone: '+591 70222334',
    featured: false,
    viewsCount: 520,
    createdDaysAgo: 45,
    segment: 'sociedad',
    subtype: 'srl',
    availablePercentage: 25,
    pitch:
      'Aporte de capital social en SRL existente con utilidades demostrables; retorno por dividendos según participación.',
  },
  {
    name: 'Textilera del Oriente SA',
    tagline: 'Acciones para la nueva línea de exportación',
    logoEmoji: '🧵',
    industryEmoji: '🏭',
    industry: 'manufactura',
    description:
      'Sociedad Anónima inscrita con 15 años en confección textil, exporta a Perú y Chile. Planta en El Alto con 60 operarios y certificación de origen para preferencias arancelarias. Emite acciones para financiar la nueva línea de exportación y ampliar capacidad en 40%.',
    department: 'La Paz',
    city: 'El Alto',
    minInvestment: 120000,
    maxInvestment: 120000,
    royaltyPercentage: 0,
    employeesRequired: 60,
    trainingWeeks: 1,
    supportLevel: 'basico',
    contactName: 'Eduardo Vásquez',
    contactEmail: 'relacioninversionistas@textileradeloriente.bo',
    contactPhone: '+591 70333445',
    featured: true,
    viewsCount: 780,
    createdDaysAgo: 60,
    segment: 'sociedad',
    subtype: 'sa',
    availablePercentage: 20,
    pitch:
      'Emisión de acciones: el inversionista accede a la propiedad accionaria de la SA con derecho a dividendos y voto en junta.',
  },
  {
    name: 'Agroindustria Beniana SA',
    tagline: 'Acciones de planta de cacao y castaña orgánica',
    logoEmoji: '🌰',
    industryEmoji: '🌾',
    industry: 'agroindustria',
    description:
      'SA agroindustrial con planta de procesamiento de cacao amazónico y castaña orgánica en Riberalta, con compra directa a 12 comunidades del TCO. Certificaciones orgánicas y de comercio justo vigentes. Abre su capital para duplicar la capacidad de tostado y lograr la certificación HACCP.',
    department: 'Beni',
    city: 'Riberalta',
    minInvestment: 150000,
    maxInvestment: 150000,
    royaltyPercentage: 0,
    employeesRequired: 45,
    trainingWeeks: 1,
    supportLevel: 'basico',
    contactName: 'Ana Carla Justiniano',
    contactEmail: 'inversion@agrobeniana.bo',
    contactPhone: '+591 70444556',
    featured: false,
    viewsCount: 340,
    createdDaysAgo: 75,
    segment: 'sociedad',
    subtype: 'sa',
    availablePercentage: 15,
    pitch:
      'Suscripción de acciones de emisión nueva para expansión industrial con mercado asegurado en exportación.',
  },
  {
    name: 'Proyecto Fexpocruz Gastronómico',
    tagline: 'Cuentas en participación para la feria mayor',
    logoEmoji: '🎪',
    industryEmoji: '🎉',
    industry: 'eventos',
    description:
      'Sociedad accidental (cuentas en participación) para operar 6 stands gastronómicos en la Feria Internacional de Cochabamba. Contrato de concesión ya adjudicado, proveedores cerrados y flujo proyectado por 21 días de feria. La sociedad se disuelve al concluir el evento con reparto de utilidades pactado.',
    department: 'Cochabamba',
    city: 'Cochabamba',
    minInvestment: 15000,
    maxInvestment: 15000,
    royaltyPercentage: 0,
    employeesRequired: 10,
    trainingWeeks: 1,
    supportLevel: 'basico',
    contactName: 'Iván Fernández',
    contactEmail: 'proyectos@fexpocruzgastronomico.bo',
    contactPhone: '+591 70555667',
    featured: false,
    viewsCount: 290,
    createdDaysAgo: 15,
    segment: 'proyecto',
    projectStart: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10),
    projectEnd: new Date(Date.now() + 90 * 86400000).toISOString().slice(0, 10),
    pitch:
      'Unión transitoria de partes para un fin específico: aporte único, participación en utilidades y disolución al cierre del evento.',
  },
  {
    name: 'Proyecto Carnaval de Oruro 2026',
    tagline: 'Conjunto invitado: estructura de palco y sponsors',
    logoEmoji: '🎭',
    industryEmoji: '🎉',
    industry: 'eventos',
    description:
      'Cuentas en participación para la producción de palco premium y activos de patrocinio en la entrada del Carnaval de Oruro. Incluye permisos, escenografía, catering y venta de hospitalidad corporativa. Proyecto con temporalidad definida: se constituye en noviembre y se disuelve tras el balance de febrero.',
    department: 'Oruro',
    city: 'Oruro',
    minInvestment: 25000,
    maxInvestment: 25000,
    royaltyPercentage: 0,
    employeesRequired: 8,
    trainingWeeks: 1,
    supportLevel: 'basico',
    contactName: 'Rocío Maldonado',
    contactEmail: 'produccion@carnavalpalcos.bo',
    contactPhone: '+591 70666778',
    featured: false,
    viewsCount: 430,
    createdDaysAgo: 200,
    segment: 'proyecto',
    projectStart: '2026-11-01',
    projectEnd: '2026-03-01',
    pitch:
      'Participación temporal con cierre contable al término del evento; trazabilidad completa de ingresos por palco y sponsors.',
  },
  {
    name: 'AgroTech Chapare',
    tagline: 'Plataforma de precios agrícolas en tiempo real',
    logoEmoji: '🌾',
    industryEmoji: '📱',
    industry: 'tecnología',
    description:
      'MIPE tecnológico validado con productores de coca legal, plátano y yuca del Chapare: app de precios de mercado por SMS y web, ya usada por 1.800 productores. Busca ronda semilla para contratar desarrollo full-time y escalar a los valles. La plataforma acompaña su formalización como empresa unipersonal ante SEPREC.',
    department: 'Cochabamba',
    city: 'Villa Tunari',
    minInvestment: 0,
    maxInvestment: 40000,
    royaltyPercentage: 0,
    employeesRequired: 3,
    trainingWeeks: 1,
    supportLevel: 'basico',
    contactName: 'Marco Antonio Mamani',
    contactEmail: 'hola@agrotechchapare.bo',
    contactPhone: '+591 70777889',
    featured: true,
    viewsCount: 610,
    createdDaysAgo: 10,
    segment: 'mipe',
    mipeStage: 'validado',
    pitch:
      'Producto con tracción real (1.800 productores activos, retención semanal del 60%) buscando capital semilla para profesionalizar el equipo técnico.',
    videoUrl: 'https://www.youtube.com/watch?v=agrotech-chapare-pitch',
    formalizationPlan:
      '1) Constitución unipersonal ante SEPREC (mes 1). 2) NIT y facturación (mes 1). 3) Registro de marca ante SENAPI (mes 2). 4) Auditoría básica del primer cierre (mes 6).',
    milestones: [
      { title: 'Constitución legal ante SEPREC', completed: false },
      { title: 'NIT y régimen general', completed: false },
      { title: '500 productores adicionales', completed: false },
      { title: 'Primer cierre auditable', completed: false },
    ],
  },
  {
    name: 'Quesería Alto Beni',
    tagline: 'Quesos artesanales de colonos alteños, listos para crecer',
    logoEmoji: '🧀',
    industryEmoji: '🥛',
    industry: 'agroindustria',
    description:
      'MIPE familiar en etapa operativa: quesos frescos y madurados de leche de 40 vacas propias, vendidos en 9 mercados de La Paz y El Alto. Sin deudas y con punto de equilibrio cubierto. Necesita capital para sala de maduración certificada y registro sanitario para ingresar a supermercados de cadena.',
    department: 'La Paz',
    city: 'Alto Beni',
    minInvestment: 0,
    maxInvestment: 18000,
    royaltyPercentage: 0,
    employeesRequired: 4,
    trainingWeeks: 1,
    supportLevel: 'basico',
    contactName: 'Herman Chipana',
    contactEmail: 'ventas@queseriaaltobeni.bo',
    contactPhone: '+591 70888990',
    featured: false,
    viewsCount: 250,
    createdDaysAgo: 20,
    segment: 'mipe',
    mipeStage: 'operativo',
    pitch:
      'Negocio en operación con ventas estables y margen del 35%; el capital acelera la certificación sanitaria y el canal supermercados.',
    videoUrl: 'https://www.youtube.com/watch?v=queseria-alto-beni',
    formalizationPlan:
      '1) Registro sanitario SENASAG (mes 2). 2) Marca ante SENAPI (mes 3). 3) Buenas prácticas de manufactura auditadas (mes 5). 4) Portafolio para supermercados (mes 7).',
    milestones: [
      { title: 'Registro sanitario SENASAG', completed: false },
      { title: 'Sala de maduración equipada', completed: false },
      { title: 'Ingreso a 2 cadenas de supermercados', completed: false },
    ],
  },
];

const FRANCHISE_SUBTYPE_OVERRIDES: Record<string, string> = {
  'Salteñitas del Sur': 'nacional',
  'Café Amazonas': 'departamental',
  'Parrilla Criolla': 'nacional',
};

export function buildSeedRows(dbNowDaysAgo: number): {
  sql: string;
  params: (string | number | null)[][];
  milestonesByIndex: Record<number, SeedMilestone[]>;
} {
  const now = Date.now();
  const rows: (string | number | null)[][] = [];
  const milestonesByIndex: Record<number, SeedMilestone[]> = {};

  seedFranchises.forEach((f, index) => {
    const segment = f.segment ?? 'franquicia';
    const createdAt = new Date(now - f.createdDaysAgo * 86400000)
      .toISOString()
      .replace('T', ' ')
      .slice(0, 19);
    const updatedAt = createdAt;
    const subtype =
      f.subtype ??
      (segment === 'franquicia'
        ? FRANCHISE_SUBTYPE_OVERRIDES[f.name] ?? 'individual'
        : null);
    rows.push([
      null,
      f.name,
      slugify(f.name),
      f.logoEmoji,
      f.tagline ?? null,
      f.description,
      f.industry,
      f.industryEmoji,
      'Bolivia',
      f.department,
      f.city,
      f.minInvestment,
      f.maxInvestment,
      'USD',
      f.royaltyPercentage,
      'mensual',
      f.estimatedRoi ?? null,
      f.employeesRequired,
      f.trainingWeeks,
      f.supportLevel,
      f.website ?? null,
      f.contactName,
      f.contactEmail,
      f.contactPhone ?? null,
      f.whatsapp ?? null,
      f.featured ? 1 : 0,
      'activa',
      f.viewsCount,
      0,
      createdAt,
      updatedAt,
      segment,
      subtype,
      segment === 'franquicia' ? null : f.minInvestment,
      f.availablePercentage ?? null,
      f.projectStart ?? null,
      f.projectEnd ?? null,
      f.mipeStage ?? null,
      f.pitch ?? null,
      f.videoUrl ?? null,
      f.formalizationPlan ?? null,
    ]);
    if (f.milestones?.length) {
      milestonesByIndex[index] = f.milestones;
    }
  });

  const sql = `
    INSERT INTO franchises (
      user_id, name, slug, logo_emoji, tagline, description, industry,
      industry_emoji, country, department, city, min_investment, max_investment,
      currency, royalty_percentage, royalty_type, estimated_roi, employees_required,
      training_weeks, support_level, website, contact_name, contact_email,
      contact_phone, whatsapp, featured, status, views_count, inquiries_count,
      created_at, updated_at, segment, subtype, sought_amount,
      available_percentage, project_start, project_end, mipe_stage, pitch,
      video_url, formalization_plan
    ) VALUES (
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
    );
  `;

  return { sql, params: rows, milestonesByIndex };
}

export const MILESTONES_INSERT_SQL = `
  INSERT INTO milestones (franchise_id, position, title, target_date, completed)
  VALUES (?, ?, ?, ?, ?);
`;
